name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode
      - uses: actions/checkout@v4

      # 2. Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 4. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 5. Install Library
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 6. Build APK
      - name: Flet Build APK
        run: |
          flet build apk --verbose --permissions photo_library

      # 7. Upload APK (FIXED PATH)
      # Menggunakan wildcard (**) agar GitHub mencari sendiri lokasi file .apk nya
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ai Metadata Pro
          path: "**/*.apk"
